/**
 * SpendingLimitAccountContract -- Aztec account contract with on-chain
 * spending limits, recipient allowlist, and timelocked parameter changes.
 *
 * Extends the standard Schnorr account by adding two extra parameters to the
 * entrypoint: `declared_amount` (Field) and `declared_recipient` (AztecAddress).
 * The contract verifies these against on-chain limits and includes them in the
 * signed hash so they cannot be forged.
 *
 * Usage:
 *   1. Compile the contract: cd contracts/spending_limit_account && nargo compile
 *   2. Copy artifact to src/artifacts/ (or adjust ARTIFACT_PATH below)
 *   3. Use SpendingLimitAccountContract instead of SchnorrAccountContract
 *      when creating the AccountManager
 *
 * Integration with aztec-client.ts:
 *   const contract = new SpendingLimitAccountContract(signingKey, {
 *     maxAmountPerTx: 1000000n,
 *     dailyLimit: 10000000n,
 *     admin: adminAddress,
 *   });
 *   const manager = await AccountManager.create(wallet, secret, contract, salt);
 */

import type { Fr as FrType } from "@aztec/foundation/curves/bn254";
import type { GrumpkinScalar as GrumpkinScalarType } from "@aztec/foundation/curves/grumpkin";
import type {
  ContractArtifact,
  FunctionAbi,
} from "@aztec/stdlib/abi";
import type {
  AuthWitnessProvider,
  EntrypointInterface,
  ChainInfo,
} from "@aztec/entrypoints/interfaces";
import type { DefaultAccountEntrypointOptions } from "@aztec/entrypoints/account";
import type { GasSettings } from "@aztec/stdlib/gas";
import type { CompleteAddress } from "@aztec/stdlib/contract";
import {
  BaseAccount,
  type Account,
  type AccountContract,
} from "@aztec/aztec.js/account";

// Must match DOM_SEP__SPENDING_LIMIT in the Noir contract (main.nr)
export const DOM_SEP_SPENDING_LIMIT = 10042;

// Path to compiled artifact. Update after running `nargo compile`.
const ARTIFACT_PATH =
  "../contracts/spending_limit_account/target/spending_limit_account_contract-SpendingLimitAccount.json";

export interface SpendingLimitConfig {
  maxAmountPerTx: bigint;
  dailyLimit: bigint;
  admin: string; // AztecAddress as 0x-prefixed 64-char hex
}

// ============================================================
// Account contract
// ============================================================

export class SpendingLimitAccountContract implements AccountContract {
  private _entrypoint: SpendingLimitEntrypoint | null = null;

  constructor(
    private signingPrivateKey: GrumpkinScalarType,
    private config: SpendingLimitConfig,
  ) {}

  /**
   * Set declared spending for the next transaction.
   * Must be called before each createNote to bind amount/recipient
   * into the signed hash so the on-chain contract can verify them.
   */
  setDeclaredSpending(amount: bigint, recipient: string): void {
    if (!this._entrypoint) {
      throw new Error(
        "Account not initialized -- getAccount() must be called first",
      );
    }
    this._entrypoint.declaredAmount = amount;
    this._entrypoint.declaredRecipient = recipient;
  }

  async getContractArtifact(): Promise<ContractArtifact> {
    // Dynamic import of the compiled Noir artifact.
    // This file is generated by `nargo compile` and must exist at ARTIFACT_PATH.
    const artifact = await import(ARTIFACT_PATH, {
      with: { type: "json" },
    });
    return artifact.default as ContractArtifact;
  }

  async getInitializationFunctionAndArgs(): Promise<{
    constructorName: string;
    constructorArgs: unknown[];
  }> {
    const { Schnorr } = await import("@aztec/foundation/crypto/schnorr");
    const { AztecAddress } = await import("@aztec/aztec.js/addresses");

    const schnorr = new Schnorr();
    const pubKey = await schnorr.computePublicKey(this.signingPrivateKey);

    return {
      constructorName: "constructor",
      constructorArgs: [
        pubKey.x,
        pubKey.y,
        this.config.maxAmountPerTx,
        this.config.dailyLimit,
        AztecAddress.fromString(this.config.admin),
      ],
    };
  }

  getAuthWitnessProvider(_address: CompleteAddress): AuthWitnessProvider {
    // Standard Schnorr signatures. The spending limit entrypoint changes
    // WHAT gets signed (combined hash including spending info), not HOW
    // the signature is produced.
    return new SpendingLimitAuthWitnessProvider(this.signingPrivateKey);
  }

  getAccount(completeAddress: CompleteAddress): Account {
    const authProvider = this.getAuthWitnessProvider(completeAddress);
    const entrypoint = new SpendingLimitEntrypoint(
      completeAddress.address,
      authProvider,
    );
    this._entrypoint = entrypoint;
    return new BaseAccount(entrypoint, authProvider, completeAddress);
  }
}

// ============================================================
// Auth witness provider (Schnorr signatures)
// ============================================================

class SpendingLimitAuthWitnessProvider implements AuthWitnessProvider {
  constructor(private signingPrivateKey: GrumpkinScalarType) {}

  async createAuthWit(messageHash: FrType): Promise<import("@aztec/stdlib/auth-witness").AuthWitness> {
    const { Schnorr } = await import("@aztec/foundation/crypto/schnorr");
    const { AuthWitness } = await import("@aztec/stdlib/auth-witness");

    const schnorr = new Schnorr();
    const signature = await schnorr.constructSignature(
      messageHash.toBuffer(),
      this.signingPrivateKey,
    );
    return new AuthWitness(messageHash, [...signature.toBuffer()]);
  }
}

// ============================================================
// Custom entrypoint (adds declared_amount + declared_recipient)
// ============================================================

/**
 * Entrypoint that encodes the spending limit contract's extended signature:
 *   entrypoint(AppPayload, u8, bool, Field, AztecAddress)
 *
 * Signs over poseidon2([payloadHash, declaredAmount, declaredRecipient],
 * DOM_SEP_SPENDING_LIMIT) instead of plain payloadHash, binding the
 * spending info to the transaction cryptographically.
 */
class SpendingLimitEntrypoint implements EntrypointInterface {
  constructor(
    private address: import("@aztec/stdlib/aztec-address").AztecAddress,
    private auth: AuthWitnessProvider,
  ) {}

  /**
   * The declared amount and recipient for the next transaction.
   * Set this before calling createTxExecutionRequest.
   */
  public declaredAmount: bigint = 0n;
  public declaredRecipient: string = "0x" + "0".repeat(64);

  async createTxExecutionRequest(
    exec: import("@aztec/stdlib/tx").ExecutionPayload,
    gasSettings: GasSettings,
    chainInfo: ChainInfo,
    options: DefaultAccountEntrypointOptions,
  ): Promise<import("@aztec/stdlib/tx").TxExecutionRequest> {
    const { Fr } = await import("@aztec/foundation/curves/bn254");
    const { FunctionSelector, encodeArguments } = await import(
      "@aztec/stdlib/abi"
    );
    const { computeOuterAuthWitHash } = await import(
      "@aztec/stdlib/auth-witness"
    );
    const { HashedValues, TxContext, TxExecutionRequest } = await import(
      "@aztec/stdlib/tx"
    );
    const { EncodedAppEntrypointCalls } = await import(
      "@aztec/entrypoints/encoding"
    );
    const { AztecAddress } = await import("@aztec/aztec.js/addresses");
    const { poseidon2HashWithSeparator } = await import(
      "@aztec/foundation/crypto/poseidon"
    );

    const { authWitnesses, capsules, extraHashedArgs } = exec;
    const { cancellable, txNonce, feePaymentMethodOptions } = options;

    // Encode function calls (same as DefaultAccountEntrypoint)
    const encodedCalls = await EncodedAppEntrypointCalls.create(
      exec.calls,
      txNonce,
    );

    // Build extended args: standard + declared_amount + declared_recipient
    const declaredAmountFr = new Fr(this.declaredAmount);
    const declaredRecipientAddr = AztecAddress.fromString(
      this.declaredRecipient,
    );

    const abi = this.getEntrypointAbi();
    const args = [
      encodedCalls,
      feePaymentMethodOptions,
      !!cancellable,
      declaredAmountFr,
      declaredRecipientAddr,
    ];
    const encodedArgs = encodeArguments(abi, args);

    const functionSelector = await FunctionSelector.fromNameAndParameters(
      abi.name,
      abi.parameters,
    );

    // Combined hash: payload + spending info
    const payloadHash = await encodedCalls.hash();
    const combinedHash = await poseidon2HashWithSeparator(
      [payloadHash, declaredAmountFr, declaredRecipientAddr.toField()],
      DOM_SEP_SPENDING_LIMIT,
    );

    // Sign over the combined hash (not just payload hash)
    const messageHash = await computeOuterAuthWitHash(
      this.address,
      chainInfo.chainId,
      chainInfo.version,
      combinedHash,
    );
    const payloadAuthWitness = await this.auth.createAuthWit(messageHash);

    const entrypointHashedArgs = await HashedValues.fromArgs(encodedArgs);
    return TxExecutionRequest.from({
      firstCallArgsHash: entrypointHashedArgs.hash,
      origin: this.address,
      functionSelector,
      txContext: new TxContext(
        chainInfo.chainId.toNumber(),
        chainInfo.version.toNumber(),
        gasSettings,
      ),
      argsOfCalls: [
        ...encodedCalls.hashedArguments,
        entrypointHashedArgs,
        ...extraHashedArgs,
      ],
      authWitnesses: [...authWitnesses, payloadAuthWitness],
      capsules,
      salt: Fr.random(),
    });
  }

  async wrapExecutionPayload(
    exec: import("@aztec/stdlib/tx").ExecutionPayload,
    chainInfo: ChainInfo,
    options: DefaultAccountEntrypointOptions,
  ): Promise<import("@aztec/stdlib/tx").ExecutionPayload> {
    const { Fr } = await import("@aztec/foundation/curves/bn254");
    const {
      FunctionCall: FunctionCallCls,
      FunctionSelector,
      encodeArguments,
    } = await import("@aztec/stdlib/abi");
    const { computeOuterAuthWitHash } = await import(
      "@aztec/stdlib/auth-witness"
    );
    const { ExecutionPayload } = await import("@aztec/stdlib/tx");
    const { EncodedAppEntrypointCalls } = await import(
      "@aztec/entrypoints/encoding"
    );
    const { AztecAddress } = await import("@aztec/aztec.js/addresses");
    const { poseidon2HashWithSeparator } = await import(
      "@aztec/foundation/crypto/poseidon"
    );

    const { authWitnesses, capsules, extraHashedArgs, feePayer } = exec;
    const { cancellable, txNonce, feePaymentMethodOptions } = options;

    const encodedCalls = await EncodedAppEntrypointCalls.create(
      exec.calls,
      txNonce,
    );

    const declaredAmountFr = new Fr(this.declaredAmount);
    const declaredRecipientAddr = AztecAddress.fromString(
      this.declaredRecipient,
    );

    const abi = this.getEntrypointAbi();
    const args = [
      encodedCalls,
      feePaymentMethodOptions,
      !!cancellable,
      declaredAmountFr,
      declaredRecipientAddr,
    ];
    const encodedArgs = encodeArguments(abi, args);
    const functionSelector = await FunctionSelector.fromNameAndParameters(
      abi.name,
      abi.parameters,
    );

    const payloadHash = await encodedCalls.hash();
    const combinedHash = await poseidon2HashWithSeparator(
      [payloadHash, declaredAmountFr, declaredRecipientAddr.toField()],
      DOM_SEP_SPENDING_LIMIT,
    );
    const messageHash = await computeOuterAuthWitHash(
      this.address,
      chainInfo.chainId,
      chainInfo.version,
      combinedHash,
    );
    const payloadAuthWitness = await this.auth.createAuthWit(messageHash);

    const entrypointCall = FunctionCallCls.from({
      name: abi.name,
      to: this.address,
      selector: functionSelector,
      type: abi.functionType,
      hideMsgSender: false,
      isStatic: abi.isStatic,
      args: encodedArgs,
      returnTypes: abi.returnTypes,
    });

    return new ExecutionPayload(
      [entrypointCall],
      [payloadAuthWitness, ...authWitnesses],
      capsules,
      [...encodedCalls.hashedArguments, ...extraHashedArgs],
      feePayer ?? this.address,
    );
  }

  /**
   * ABI for the extended entrypoint signature. Matches the Noir contract's
   * entrypoint function: (AppPayload, u8, bool, Field, AztecAddress).
   */
  private getEntrypointAbi(): FunctionAbi {
    return {
      name: "entrypoint",
      isInitializer: false,
      functionType: "private",
      isOnlySelf: false,
      isStatic: false,
      parameters: [
        // Standard parameters (identical to DefaultAccountEntrypoint)
        {
          name: "app_payload",
          type: {
            kind: "struct",
            path: "authwit::entrypoint::app::AppPayload",
            fields: [
              {
                name: "function_calls",
                type: {
                  kind: "array",
                  length: 5,
                  type: {
                    kind: "struct",
                    path: "authwit::entrypoint::function_call::FunctionCall",
                    fields: [
                      { name: "args_hash", type: { kind: "field" } },
                      {
                        name: "function_selector",
                        type: {
                          kind: "struct",
                          path: "authwit::aztec::protocol_types::abis::function_selector::FunctionSelector",
                          fields: [
                            {
                              name: "inner",
                              type: {
                                kind: "integer",
                                sign: "unsigned",
                                width: 32,
                              },
                            },
                          ],
                        },
                      },
                      {
                        name: "target_address",
                        type: {
                          kind: "struct",
                          path: "authwit::aztec::protocol_types::address::AztecAddress",
                          fields: [
                            { name: "inner", type: { kind: "field" } },
                          ],
                        },
                      },
                      { name: "is_public", type: { kind: "boolean" } },
                      { name: "hide_msg_sender", type: { kind: "boolean" } },
                      { name: "is_static", type: { kind: "boolean" } },
                    ],
                  },
                },
              },
              { name: "tx_nonce", type: { kind: "field" } },
            ],
          },
          visibility: "public",
        },
        {
          name: "fee_payment_method",
          type: { kind: "integer", sign: "unsigned", width: 8 },
        },
        {
          name: "cancellable",
          type: { kind: "boolean" },
        },
        // Extended parameters for spending limit enforcement
        {
          name: "declared_amount",
          type: { kind: "field" },
        },
        {
          name: "declared_recipient",
          type: {
            kind: "struct",
            path: "authwit::aztec::protocol_types::address::AztecAddress",
            fields: [{ name: "inner", type: { kind: "field" } }],
          },
        },
      ],
      returnTypes: [],
      errorTypes: {},
    } as FunctionAbi;
  }
}
